### PR TITLE
Add cli for creating controllers and middlewares

### PR DESCRIPTION
**Pull request by 41i-6h0rb4n1**

### CODE REVIEW

**Review by peter279k — COMMENTED** [review]
Do you try to resolve issue #36?

And I think this approach is not good because it's native CLI and we cannot verify every command works.

I prefer using the [symfony/console](https://symfony.com/doc/current/components/console.html) to create related console :).

**Comment by izniburak** [comment]
Hi @41i-6h0rb4n1 ,
Firstly, Thank you for your support and effort. 
I agree with @peter279k . I think, we can use symfony/console package as a development dependency in order to make mini console app for this project. I consider that we can work on this PR. Actually, I was working on a feature like that, but I couldn't complete yet due to busy. We can go over the this console application idea.

**Comment by peter279k** [comment]
> 
> 
> Hi @41i-6h0rb4n1 ,
> Firstly, Thank you for your support and effort.
> I agree with @peter279k . I think, we can use symfony/console package as a development dependency in order to make mini console app for this project. I consider that we can work on this PR. Actually, I was working on a feature like that, but I couldn't complete yet due to busy. We can go over the this console application idea.

Thanks for your reply, @izniburak. I think you can close PR and create your PR that your console :).

**Comment by 41i-6h0rb4n1** [comment]
Hi guys.
Thanks for your answers.

So I will try symfony/console.

**Pull request closed without merging**
